### ISSUE TITLE
请问Bootloader是怎么写的呀

### ISSUE THREAD

**Issue by jiuxiaxixi** [peng-zhihui/ST-Link-Nano#3]
我看到有bootloader 的bin文件，但是这个bootloader 是自己写的么？

**Comment by jiuxiaxixi** [comment]
@peng-zhihui  可以分享下Clion调试STM32的项目的模版么？

**Comment by peng-zhihui** [comment]
有的，FOC-Lite那个项目就是

**Comment by jiuxiaxixi** [comment]
@peng-zhihui  感谢~
