### ISSUE TITLE
这个stlink一定要用f103cbt6吗？f103c8t6能不能用？

### ISSUE THREAD

**Issue by mu-youli** [peng-zhihui/ST-Link-Nano#6]
看了里面只有一个BootLoader.bin文件，大小是16KB，我不太确定c8t6的64kb够不够用。是直接烧录进去就行了吗？

**Comment by peng-zhihui** [comment]
可以，一样的

**Comment by mu-youli** [comment]
> 可以，一样的

ohhhhh!!!  大佬回我了！ 昨天收到邮件激动了一晚上！   板子已经下单开打了！元器件也已经买好了！突然我就充满动力了！

   感谢稚晖大佬回复！追随你脚步的路上突然充满动力！我会更多的复刻你的作品并做出创新，越来越接近你的高度的！

**Comment by tai-youli** [comment]
> 可以，一样的

ohhhhh!!!  大佬回我了！ 昨天收到邮件激动了一晚上！   板子已经下单开打了！元器件也已经买好了！突然我就充满动力了！

   感谢稚晖大佬回复！追随你脚步的路上突然充满动力！我会更多的复刻你的作品并做出创新，越来越接近你的高度的！
