### ISSUE TITLE
[Help] 用CC线无法识别ST-Link,但是USBA-typeC可以正常使用

### ISSUE THREAD

**Issue by Last-ID** [peng-zhihui/ST-Link-Nano#7]
如题，CC1，CC2口无下拉电阻无法正常供电，添加5.1K下拉电阻后，可以正常供电，但是无法识别到stlink

**在实际复刻过程中，为了方便焊接，更改了连接器母座型号**，下图为16Pin Type-C母座原理图，其他部分电路与稚晖君的保持一致
![image](https://user-images.githubusercontent.com/44721512/165670500-8a93b211-5d0d-4b44-afc0-4e16544082b2.png)

**Comment by peng-zhihui** [comment]
你这图里3个USB_P，明显是原理图画错了啊

**Comment by Last-ID** [comment]
OK，把线纠正过来之后加了俩下拉电阻，CC线可以正常使用了
![image](https://user-images.githubusercontent.com/44721512/169747891-831432f6-caf7-4de1-bac8-f8c5e7e20f6e.png)
